#This Launcher starts directly

import minecraft_launcher_lib
import subprocess
import os

# Get the Minecraft Directory of your System
minecraft_directory = minecraft_launcher_lib.utils.get_minecraft_directory()

#Install Minecraft
latest_release = minecraft_launcher_lib.utils.get_latest_version()["release"]
minecraft_launcher_lib.install.install_minecraft_version(latest_release, minecraft_directory)

#Generate Options
options = {"username": "ehrenWoingenau", "uuid": "9e16d3df44ee43c3a0b2f498013021f4", "token": "eyJraWQiOiJhYzg0YSIsImFsZyI6IkhTMjU2In0.eyJ4dWlkIjoiMjUzNTQ0NjU0MjAzMzg4MiIsImFnZyI6IkFkdWx0Iiwic3ViIjoiOTkwMTcxOWYtN2MxZS00ODYxLTg1NTctYjRkNTdmYTUwOTI0IiwiYXV0aCI6IlhCT1giLCJucyI6ImRlZmF1bHQiLCJyb2xlcyI6W10sImlzcyI6ImF1dGhlbnRpY2F0aW9uIiwicGxhdGZvcm0iOiJVTktOT1dOIiwieXVpZCI6IjM3YjIxZDM2OTA4M2JhYjMyZDU4YjliZWIyZDIxMWE3IiwibmJmIjoxNjc3MzE5NjI2LCJleHAiOjE2Nzc0MDYwMjYsImlhdCI6MTY3NzMxOTYyNn0.eZtYnippRVWAFM0le7G7ONKyUNtvwIaWZCtyB6hqjRg"}

#Get Minecraft Command
minecraft_command = minecraft_launcher_lib.command.get_minecraft_command(latest_release, minecraft_directory, options)

#Start Minecraft
subprocess.call(minecraft_command)
